[versions]
activityKtx = "1.9.0"
androidCoreTest = "2.2.0"
androidGradlePlugin = "8.13.2"
androidTools = "31.9.1"
appCompat = "1.7.0"
appcompatV7 = "28.0.0"
assertjCore = "3.26.0"
cardview = "1.0.0"
compose = "1.8.2"
composeActivity = "1.9.0"
constraintLayout = "2.1.4"
detekt = "1.23.6"
espresso = "3.5.1"
espressoCore = "3.0.2"
espressoRecyclerViewUtils = "1.0"
fragmentKtx = "1.7.1"
glide = "4.16.0"
gson = "2.11.0"
junit = "4.13.2"
junitKtx = "1.1.5"
junitParamTest = "1.1.1"
koin = "4.1.1"
kotlin = "2.1.0"
kotlinCoroutines = "1.10.1"
kotlinLogging = "6.0.9"
kotlinTurbine = "1.1.0"
kotlinxDatetime = "0.6.2"
ksp = "2.1.0-1.0.29"
ktor = "3.0.1"
ktxCore = "1.13.1"
leakCanary = "2.14"
legacySupport = "1.0.0"
lifecycle = "2.8.7"
materialTheme = "1.12.0"
mockWebServer = "4.12.0"
mockitoCore = "5.12.0"
mockitoKotlin = "1.6.0"
navigationComposeKmp = "2.9.0"
room = "2.7.0"
runner = "1.0.2"
sqlite = "2.5.0"
splashScreen = "1.0.1"
testCore = "1.5.0"
testJunitExt = "1.1.5"
testJunitKtExtVersions = "1.1.5"
testOrchestrator = "1.4.2"
testRules = "1.5.0"
testRunnerVersion = "1.5.2"
testUiAutomator = "2.3.0"
truth = "1.4.2"

[libraries]
activityKtx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
appCompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
cardView = { module = "androidx.cardview:cardview", version.ref = "cardview" }
composeActivity = { module = "androidx.activity:activity-compose", version.ref = "composeActivity" }
constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }
detektFormattion = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
fragmentKtx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glideCompile = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidxCompose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-composeViewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
kotlinCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinCoroutines" }
kotlinCoroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlinLogging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlinLogging" }
kotlinxDatetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
ktxCore = { module = "androidx.core:core-ktx", version.ref = "ktxCore" }
navigationComposeKmp = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigationComposeKmp" }
ktor-clientCio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-clientContentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-clientCore = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-clientDarwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-clientLogging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-clientMock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
ktor-serializationJson = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
leakCanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakCanary" }
legacySupport = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacySupport" }
lifecycleViewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycle" }
materialTheme = { module = "com.google.android.material:material", version.ref = "materialTheme" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
splashLibrary = { module = "androidx.core:core-splashscreen", version.ref = "splashScreen" }
sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }

# Define test libraries
androidCoreTesting = { module = "androidx.arch.core:core-testing", version.ref = "androidCoreTest" }
assertjCore = { module = "org.assertj:assertj-core", version.ref = "assertjCore" }
junit = { module = "junit:junit", version.ref = "junit" }
junitKtx = { module = "androidx.test.ext:junit-ktx", version.ref = "junitKtx" }
junitParamTest = { module = "pl.pragmatists:JUnitParams", version.ref = "junitParamTest" }
kotlinCoroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinCoroutines" }
kotlinTurbine = { module = "app.cash.turbine:turbine", version.ref = "kotlinTurbine" }
mockWebServer = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "mockWebServer" }
mockitoCore = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
mockitoKotlin = { module = "com.nhaarman:mockito-kotlin", version.ref = "mockitoKotlin" }
orchestrator = { module = "androidx.test:orchestrator", version.ref = "testOrchestrator" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }

# Define android test libraries
espressoContrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "espresso" }
espressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
espressoIdlingResource = { module = "androidx.test.espresso:espresso-idling-resource", version.ref = "espresso" }
espressoIntents = { module = "androidx.test.espresso:espresso-intents", version.ref = "espresso" }
espressoRecyclerViewUtils = { module = "it.xabaras.android.espresso:recyclerview-child-actions", version.ref = "espressoRecyclerViewUtils" }
testCore = { module = "androidx.test:core", version.ref = "testCore" }
testJunitExt = { module = "androidx.test.ext:junit", version.ref = "testJunitExt" }
testJunitKtExtVersions = { module = "androidx.test.ext:junit-ktx", version.ref = "testJunitKtExtVersions" }
testRules = { module = "androidx.test:rules", version.ref = "testRules" }
testRunner = { module = "androidx.test:runner", version.ref = "testRunnerVersion" }
testUiAutomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "testUiAutomator" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
androidLibrary = { id = "com.android.library", version.ref = "androidGradlePlugin" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose" }
detektPlugin = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "room" }

# Define bundles/groups of libraries
[bundles]
androidFramework = ["activityKtx", "appCompat", "cardView", "constraintLayout", "fragmentKtx", "ktxCore", "legacySupport", "lifecycleViewmodel", "materialTheme", "splashLibrary"]
androidTest = ["espressoContrib", "espressoCore", "espressoIdlingResource", "espressoIntents", "espressoRecyclerViewUtils", "mockWebServer", "testCore", "testJunitExt", "testJunitKtExtVersions", "testRules", "testUiAutomator"]
detekt = ["detektFormattion"]
ktorAndroid = ["ktor-clientCio"]
ktorCommon = ["ktor-clientCore", "ktor-clientContentNegotiation", "ktor-serializationJson", "ktor-clientLogging"]
ktorIos = ["ktor-clientDarwin"]
test = ["androidCoreTesting", "assertjCore", "junit", "junitParamTest", "kotlinCoroutinesTest", "kotlinTurbine", "mockitoCore", "mockitoKotlin", "testRules", "truth"]
