package com.ebdz.data.local

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor
import com.ebdz.data.local.dao.SimpleDao
import com.ebdz.data.local.entity.SimpleEntity

/**
 * Database class.
 */
@Database(entities = [SimpleEntity::class], version = 1, exportSchema = true)
@ConstructedBy(TaskDatabaseConstructor::class)
abstract class TaskDatabase : RoomDatabase() {
    abstract fun simpleDao(): SimpleDao
}

/**
 * Room KMP database constructor. The `actual` implementations are generated by the Room
 * compiler (KSP) for each target, so no hand-written `actual` is required - this `expect`
 * is only needed because `@Database` classes targeting non-JVM platforms must declare one.
 */
@Suppress("NO_ACTUAL_FOR_EXPECT", "KotlinNoActualForExpect")
expect object TaskDatabaseConstructor : RoomDatabaseConstructor<TaskDatabase> {
    override fun initialize(): TaskDatabase
}
